version: '3'

services:
  server:
    build: .
    command: ./entrypoint.sh
    volumes:
      - ./web:/srv/django
      - ./shared_static:/var/www/storage/goldennum:rw
    restart: always

  httpd:
    image: abiosoft/caddy:1.0.3-no-stats
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./shared_static:/var/www/storage/goldennum:ro
    ports:
      - "8083:8080"
    links:
      - server
    restart: always