version: '3'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8080 -w4 web.wsgi
    volumes:
      - ./web:/srv/django
      - /var/www/storage/goldennum:/var/www/storage/goldennum
    ports:
      - "8083:8080"
    restart: always
